// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.5
// source: connect_tool.proto

package connecttool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectToolService_InitSteam_FullMethodName          = "/connecttool.ConnectToolService/InitSteam"
	ConnectToolService_CreateLobby_FullMethodName        = "/connecttool.ConnectToolService/CreateLobby"
	ConnectToolService_JoinLobby_FullMethodName          = "/connecttool.ConnectToolService/JoinLobby"
	ConnectToolService_LeaveLobby_FullMethodName         = "/connecttool.ConnectToolService/LeaveLobby"
	ConnectToolService_GetLobbyInfo_FullMethodName       = "/connecttool.ConnectToolService/GetLobbyInfo"
	ConnectToolService_GetFriendLobbies_FullMethodName   = "/connecttool.ConnectToolService/GetFriendLobbies"
	ConnectToolService_InviteFriend_FullMethodName       = "/connecttool.ConnectToolService/InviteFriend"
	ConnectToolService_StartVPN_FullMethodName           = "/connecttool.ConnectToolService/StartVPN"
	ConnectToolService_StopVPN_FullMethodName            = "/connecttool.ConnectToolService/StopVPN"
	ConnectToolService_GetVPNStatus_FullMethodName       = "/connecttool.ConnectToolService/GetVPNStatus"
	ConnectToolService_GetVPNRoutingTable_FullMethodName = "/connecttool.ConnectToolService/GetVPNRoutingTable"
)

// ConnectToolServiceClient is the client API for ConnectToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectToolServiceClient interface {
	// Steam Initialization
	InitSteam(ctx context.Context, in *InitSteamRequest, opts ...grpc.CallOption) (*InitSteamResponse, error)
	// Lobby Management
	CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error)
	JoinLobby(ctx context.Context, in *JoinLobbyRequest, opts ...grpc.CallOption) (*JoinLobbyResponse, error)
	LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error)
	GetLobbyInfo(ctx context.Context, in *GetLobbyInfoRequest, opts ...grpc.CallOption) (*GetLobbyInfoResponse, error)
	GetFriendLobbies(ctx context.Context, in *GetFriendLobbiesRequest, opts ...grpc.CallOption) (*GetFriendLobbiesResponse, error)
	InviteFriend(ctx context.Context, in *InviteFriendRequest, opts ...grpc.CallOption) (*InviteFriendResponse, error)
	// VPN Management
	StartVPN(ctx context.Context, in *StartVPNRequest, opts ...grpc.CallOption) (*StartVPNResponse, error)
	StopVPN(ctx context.Context, in *StopVPNRequest, opts ...grpc.CallOption) (*StopVPNResponse, error)
	GetVPNStatus(ctx context.Context, in *GetVPNStatusRequest, opts ...grpc.CallOption) (*GetVPNStatusResponse, error)
	GetVPNRoutingTable(ctx context.Context, in *GetVPNRoutingTableRequest, opts ...grpc.CallOption) (*GetVPNRoutingTableResponse, error)
}

type connectToolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectToolServiceClient(cc grpc.ClientConnInterface) ConnectToolServiceClient {
	return &connectToolServiceClient{cc}
}

func (c *connectToolServiceClient) InitSteam(ctx context.Context, in *InitSteamRequest, opts ...grpc.CallOption) (*InitSteamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitSteamResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_InitSteam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLobbyResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_CreateLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) JoinLobby(ctx context.Context, in *JoinLobbyRequest, opts ...grpc.CallOption) (*JoinLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinLobbyResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_JoinLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveLobbyResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_LeaveLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) GetLobbyInfo(ctx context.Context, in *GetLobbyInfoRequest, opts ...grpc.CallOption) (*GetLobbyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLobbyInfoResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_GetLobbyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) GetFriendLobbies(ctx context.Context, in *GetFriendLobbiesRequest, opts ...grpc.CallOption) (*GetFriendLobbiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendLobbiesResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_GetFriendLobbies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) InviteFriend(ctx context.Context, in *InviteFriendRequest, opts ...grpc.CallOption) (*InviteFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteFriendResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_InviteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) StartVPN(ctx context.Context, in *StartVPNRequest, opts ...grpc.CallOption) (*StartVPNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVPNResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_StartVPN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) StopVPN(ctx context.Context, in *StopVPNRequest, opts ...grpc.CallOption) (*StopVPNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVPNResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_StopVPN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) GetVPNStatus(ctx context.Context, in *GetVPNStatusRequest, opts ...grpc.CallOption) (*GetVPNStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVPNStatusResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_GetVPNStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectToolServiceClient) GetVPNRoutingTable(ctx context.Context, in *GetVPNRoutingTableRequest, opts ...grpc.CallOption) (*GetVPNRoutingTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVPNRoutingTableResponse)
	err := c.cc.Invoke(ctx, ConnectToolService_GetVPNRoutingTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectToolServiceServer is the server API for ConnectToolService service.
// All implementations must embed UnimplementedConnectToolServiceServer
// for forward compatibility.
type ConnectToolServiceServer interface {
	// Steam Initialization
	InitSteam(context.Context, *InitSteamRequest) (*InitSteamResponse, error)
	// Lobby Management
	CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error)
	JoinLobby(context.Context, *JoinLobbyRequest) (*JoinLobbyResponse, error)
	LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error)
	GetLobbyInfo(context.Context, *GetLobbyInfoRequest) (*GetLobbyInfoResponse, error)
	GetFriendLobbies(context.Context, *GetFriendLobbiesRequest) (*GetFriendLobbiesResponse, error)
	InviteFriend(context.Context, *InviteFriendRequest) (*InviteFriendResponse, error)
	// VPN Management
	StartVPN(context.Context, *StartVPNRequest) (*StartVPNResponse, error)
	StopVPN(context.Context, *StopVPNRequest) (*StopVPNResponse, error)
	GetVPNStatus(context.Context, *GetVPNStatusRequest) (*GetVPNStatusResponse, error)
	GetVPNRoutingTable(context.Context, *GetVPNRoutingTableRequest) (*GetVPNRoutingTableResponse, error)
	mustEmbedUnimplementedConnectToolServiceServer()
}

// UnimplementedConnectToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectToolServiceServer struct{}

func (UnimplementedConnectToolServiceServer) InitSteam(context.Context, *InitSteamRequest) (*InitSteamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitSteam not implemented")
}
func (UnimplementedConnectToolServiceServer) CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLobby not implemented")
}
func (UnimplementedConnectToolServiceServer) JoinLobby(context.Context, *JoinLobbyRequest) (*JoinLobbyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinLobby not implemented")
}
func (UnimplementedConnectToolServiceServer) LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveLobby not implemented")
}
func (UnimplementedConnectToolServiceServer) GetLobbyInfo(context.Context, *GetLobbyInfoRequest) (*GetLobbyInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLobbyInfo not implemented")
}
func (UnimplementedConnectToolServiceServer) GetFriendLobbies(context.Context, *GetFriendLobbiesRequest) (*GetFriendLobbiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendLobbies not implemented")
}
func (UnimplementedConnectToolServiceServer) InviteFriend(context.Context, *InviteFriendRequest) (*InviteFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteFriend not implemented")
}
func (UnimplementedConnectToolServiceServer) StartVPN(context.Context, *StartVPNRequest) (*StartVPNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVPN not implemented")
}
func (UnimplementedConnectToolServiceServer) StopVPN(context.Context, *StopVPNRequest) (*StopVPNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVPN not implemented")
}
func (UnimplementedConnectToolServiceServer) GetVPNStatus(context.Context, *GetVPNStatusRequest) (*GetVPNStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVPNStatus not implemented")
}
func (UnimplementedConnectToolServiceServer) GetVPNRoutingTable(context.Context, *GetVPNRoutingTableRequest) (*GetVPNRoutingTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVPNRoutingTable not implemented")
}
func (UnimplementedConnectToolServiceServer) mustEmbedUnimplementedConnectToolServiceServer() {}
func (UnimplementedConnectToolServiceServer) testEmbeddedByValue()                            {}

// UnsafeConnectToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectToolServiceServer will
// result in compilation errors.
type UnsafeConnectToolServiceServer interface {
	mustEmbedUnimplementedConnectToolServiceServer()
}

func RegisterConnectToolServiceServer(s grpc.ServiceRegistrar, srv ConnectToolServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectToolService_ServiceDesc, srv)
}

func _ConnectToolService_InitSteam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSteamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).InitSteam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_InitSteam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).InitSteam(ctx, req.(*InitSteamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_CreateLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).CreateLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_CreateLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).CreateLobby(ctx, req.(*CreateLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_JoinLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).JoinLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_JoinLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).JoinLobby(ctx, req.(*JoinLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_LeaveLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).LeaveLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_LeaveLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).LeaveLobby(ctx, req.(*LeaveLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_GetLobbyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLobbyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).GetLobbyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_GetLobbyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).GetLobbyInfo(ctx, req.(*GetLobbyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_GetFriendLobbies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendLobbiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).GetFriendLobbies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_GetFriendLobbies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).GetFriendLobbies(ctx, req.(*GetFriendLobbiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_InviteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).InviteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_InviteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).InviteFriend(ctx, req.(*InviteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_StartVPN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVPNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).StartVPN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_StartVPN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).StartVPN(ctx, req.(*StartVPNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_StopVPN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVPNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).StopVPN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_StopVPN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).StopVPN(ctx, req.(*StopVPNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_GetVPNStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVPNStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).GetVPNStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_GetVPNStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).GetVPNStatus(ctx, req.(*GetVPNStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectToolService_GetVPNRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVPNRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectToolServiceServer).GetVPNRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectToolService_GetVPNRoutingTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectToolServiceServer).GetVPNRoutingTable(ctx, req.(*GetVPNRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectToolService_ServiceDesc is the grpc.ServiceDesc for ConnectToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connecttool.ConnectToolService",
	HandlerType: (*ConnectToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitSteam",
			Handler:    _ConnectToolService_InitSteam_Handler,
		},
		{
			MethodName: "CreateLobby",
			Handler:    _ConnectToolService_CreateLobby_Handler,
		},
		{
			MethodName: "JoinLobby",
			Handler:    _ConnectToolService_JoinLobby_Handler,
		},
		{
			MethodName: "LeaveLobby",
			Handler:    _ConnectToolService_LeaveLobby_Handler,
		},
		{
			MethodName: "GetLobbyInfo",
			Handler:    _ConnectToolService_GetLobbyInfo_Handler,
		},
		{
			MethodName: "GetFriendLobbies",
			Handler:    _ConnectToolService_GetFriendLobbies_Handler,
		},
		{
			MethodName: "InviteFriend",
			Handler:    _ConnectToolService_InviteFriend_Handler,
		},
		{
			MethodName: "StartVPN",
			Handler:    _ConnectToolService_StartVPN_Handler,
		},
		{
			MethodName: "StopVPN",
			Handler:    _ConnectToolService_StopVPN_Handler,
		},
		{
			MethodName: "GetVPNStatus",
			Handler:    _ConnectToolService_GetVPNStatus_Handler,
		},
		{
			MethodName: "GetVPNRoutingTable",
			Handler:    _ConnectToolService_GetVPNRoutingTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect_tool.proto",
}
