// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: connect_tool.proto

package connecttool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitSteamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSteamRequest) Reset() {
	*x = InitSteamRequest{}
	mi := &file_connect_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSteamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSteamRequest) ProtoMessage() {}

func (x *InitSteamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSteamRequest.ProtoReflect.Descriptor instead.
func (*InitSteamRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{0}
}

type InitSteamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSteamResponse) Reset() {
	*x = InitSteamResponse{}
	mi := &file_connect_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSteamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSteamResponse) ProtoMessage() {}

func (x *InitSteamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSteamResponse.ProtoReflect.Descriptor instead.
func (*InitSteamResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{1}
}

func (x *InitSteamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitSteamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_connect_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{2}
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LobbyId       string                 `protobuf:"bytes,2,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_connect_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLobbyResponse) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_connect_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_connect_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinLobbyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LeaveLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyRequest) Reset() {
	*x = LeaveLobbyRequest{}
	mi := &file_connect_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyRequest) ProtoMessage() {}

func (x *LeaveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{6}
}

type LeaveLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyResponse) Reset() {
	*x = LeaveLobbyResponse{}
	mi := &file_connect_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyResponse) ProtoMessage() {}

func (x *LeaveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LobbyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ping          int32                  `protobuf:"varint,3,opt,name=ping,proto3" json:"ping,omitempty"`
	RelayInfo     string                 `protobuf:"bytes,4,opt,name=relay_info,json=relayInfo,proto3" json:"relay_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyMember) Reset() {
	*x = LobbyMember{}
	mi := &file_connect_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyMember) ProtoMessage() {}

func (x *LobbyMember) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyMember.ProtoReflect.Descriptor instead.
func (*LobbyMember) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{8}
}

func (x *LobbyMember) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *LobbyMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyMember) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *LobbyMember) GetRelayInfo() string {
	if x != nil {
		return x.RelayInfo
	}
	return ""
}

type GetLobbyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLobbyInfoRequest) Reset() {
	*x = GetLobbyInfoRequest{}
	mi := &file_connect_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbyInfoRequest) ProtoMessage() {}

func (x *GetLobbyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLobbyInfoRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{9}
}

type GetLobbyInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInLobby     bool                   `protobuf:"varint,1,opt,name=is_in_lobby,json=isInLobby,proto3" json:"is_in_lobby,omitempty"`
	LobbyId       string                 `protobuf:"bytes,2,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Members       []*LobbyMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLobbyInfoResponse) Reset() {
	*x = GetLobbyInfoResponse{}
	mi := &file_connect_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbyInfoResponse) ProtoMessage() {}

func (x *GetLobbyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLobbyInfoResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{10}
}

func (x *GetLobbyInfoResponse) GetIsInLobby() bool {
	if x != nil {
		return x.IsInLobby
	}
	return false
}

func (x *GetLobbyInfoResponse) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *GetLobbyInfoResponse) GetMembers() []*LobbyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FriendLobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LobbyId       string                 `protobuf:"bytes,3,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendLobby) Reset() {
	*x = FriendLobby{}
	mi := &file_connect_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendLobby) ProtoMessage() {}

func (x *FriendLobby) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendLobby.ProtoReflect.Descriptor instead.
func (*FriendLobby) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{11}
}

func (x *FriendLobby) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *FriendLobby) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendLobby) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type GetFriendLobbiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendLobbiesRequest) Reset() {
	*x = GetFriendLobbiesRequest{}
	mi := &file_connect_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendLobbiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendLobbiesRequest) ProtoMessage() {}

func (x *GetFriendLobbiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendLobbiesRequest.ProtoReflect.Descriptor instead.
func (*GetFriendLobbiesRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{12}
}

type GetFriendLobbiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobbies       []*FriendLobby         `protobuf:"bytes,1,rep,name=lobbies,proto3" json:"lobbies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendLobbiesResponse) Reset() {
	*x = GetFriendLobbiesResponse{}
	mi := &file_connect_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendLobbiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendLobbiesResponse) ProtoMessage() {}

func (x *GetFriendLobbiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendLobbiesResponse.ProtoReflect.Descriptor instead.
func (*GetFriendLobbiesResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{13}
}

func (x *GetFriendLobbiesResponse) GetLobbies() []*FriendLobby {
	if x != nil {
		return x.Lobbies
	}
	return nil
}

type InviteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendSteamId string                 `protobuf:"bytes,1,opt,name=friend_steam_id,json=friendSteamId,proto3" json:"friend_steam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteFriendRequest) Reset() {
	*x = InviteFriendRequest{}
	mi := &file_connect_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteFriendRequest) ProtoMessage() {}

func (x *InviteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteFriendRequest.ProtoReflect.Descriptor instead.
func (*InviteFriendRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{14}
}

func (x *InviteFriendRequest) GetFriendSteamId() string {
	if x != nil {
		return x.FriendSteamId
	}
	return ""
}

type InviteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteFriendResponse) Reset() {
	*x = InviteFriendResponse{}
	mi := &file_connect_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteFriendResponse) ProtoMessage() {}

func (x *InviteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteFriendResponse.ProtoReflect.Descriptor instead.
func (*InviteFriendResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{15}
}

func (x *InviteFriendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartVPNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`     // e.g., "10.0.0.0"
	Mask          string                 `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"` // e.g., "255.255.255.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVPNRequest) Reset() {
	*x = StartVPNRequest{}
	mi := &file_connect_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVPNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVPNRequest) ProtoMessage() {}

func (x *StartVPNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVPNRequest.ProtoReflect.Descriptor instead.
func (*StartVPNRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{16}
}

func (x *StartVPNRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StartVPNRequest) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type StartVPNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVPNResponse) Reset() {
	*x = StartVPNResponse{}
	mi := &file_connect_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVPNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVPNResponse) ProtoMessage() {}

func (x *StartVPNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVPNResponse.ProtoReflect.Descriptor instead.
func (*StartVPNResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{17}
}

func (x *StartVPNResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartVPNResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopVPNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVPNRequest) Reset() {
	*x = StopVPNRequest{}
	mi := &file_connect_tool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVPNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVPNRequest) ProtoMessage() {}

func (x *StopVPNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVPNRequest.ProtoReflect.Descriptor instead.
func (*StopVPNRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{18}
}

type StopVPNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVPNResponse) Reset() {
	*x = StopVPNResponse{}
	mi := &file_connect_tool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVPNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVPNResponse) ProtoMessage() {}

func (x *StopVPNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVPNResponse.ProtoReflect.Descriptor instead.
func (*StopVPNResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{19}
}

func (x *StopVPNResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VPNStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PacketsSent     uint64                 `protobuf:"varint,1,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	BytesSent       uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	PacketsReceived uint64                 `protobuf:"varint,3,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	BytesReceived   uint64                 `protobuf:"varint,4,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	PacketsDropped  uint64                 `protobuf:"varint,5,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VPNStats) Reset() {
	*x = VPNStats{}
	mi := &file_connect_tool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNStats) ProtoMessage() {}

func (x *VPNStats) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNStats.ProtoReflect.Descriptor instead.
func (*VPNStats) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{20}
}

func (x *VPNStats) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *VPNStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *VPNStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *VPNStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *VPNStats) GetPacketsDropped() uint64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

type GetVPNStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPNStatusRequest) Reset() {
	*x = GetVPNStatusRequest{}
	mi := &file_connect_tool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPNStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPNStatusRequest) ProtoMessage() {}

func (x *GetVPNStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPNStatusRequest.ProtoReflect.Descriptor instead.
func (*GetVPNStatusRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{21}
}

type GetVPNStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LocalIp       string                 `protobuf:"bytes,2,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Stats         *VPNStats              `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPNStatusResponse) Reset() {
	*x = GetVPNStatusResponse{}
	mi := &file_connect_tool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPNStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPNStatusResponse) ProtoMessage() {}

func (x *GetVPNStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPNStatusResponse.ProtoReflect.Descriptor instead.
func (*GetVPNStatusResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{22}
}

func (x *GetVPNStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetVPNStatusResponse) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *GetVPNStatusResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GetVPNStatusResponse) GetStats() *VPNStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type VPNRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            uint32                 `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsLocal       bool                   `protobuf:"varint,3,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNRoute) Reset() {
	*x = VPNRoute{}
	mi := &file_connect_tool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNRoute) ProtoMessage() {}

func (x *VPNRoute) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNRoute.ProtoReflect.Descriptor instead.
func (*VPNRoute) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{23}
}

func (x *VPNRoute) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

func (x *VPNRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VPNRoute) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

type GetVPNRoutingTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPNRoutingTableRequest) Reset() {
	*x = GetVPNRoutingTableRequest{}
	mi := &file_connect_tool_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPNRoutingTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPNRoutingTableRequest) ProtoMessage() {}

func (x *GetVPNRoutingTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPNRoutingTableRequest.ProtoReflect.Descriptor instead.
func (*GetVPNRoutingTableRequest) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{24}
}

type GetVPNRoutingTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*VPNRoute            `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPNRoutingTableResponse) Reset() {
	*x = GetVPNRoutingTableResponse{}
	mi := &file_connect_tool_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPNRoutingTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPNRoutingTableResponse) ProtoMessage() {}

func (x *GetVPNRoutingTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connect_tool_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPNRoutingTableResponse.ProtoReflect.Descriptor instead.
func (*GetVPNRoutingTableResponse) Descriptor() ([]byte, []int) {
	return file_connect_tool_proto_rawDescGZIP(), []int{25}
}

func (x *GetVPNRoutingTableResponse) GetRoutes() []*VPNRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_connect_tool_proto protoreflect.FileDescriptor

const file_connect_tool_proto_rawDesc = "" +
	"\n" +
	"\x12connect_tool.proto\x12\vconnecttool\"\x12\n" +
	"\x10InitSteamRequest\"G\n" +
	"\x11InitSteamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12CreateLobbyRequest\"J\n" +
	"\x13CreateLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\blobby_id\x18\x02 \x01(\tR\alobbyId\"-\n" +
	"\x10JoinLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\"G\n" +
	"\x11JoinLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11LeaveLobbyRequest\".\n" +
	"\x12LeaveLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\vLobbyMember\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04ping\x18\x03 \x01(\x05R\x04ping\x12\x1d\n" +
	"\n" +
	"relay_info\x18\x04 \x01(\tR\trelayInfo\"\x15\n" +
	"\x13GetLobbyInfoRequest\"\x85\x01\n" +
	"\x14GetLobbyInfoResponse\x12\x1e\n" +
	"\vis_in_lobby\x18\x01 \x01(\bR\tisInLobby\x12\x19\n" +
	"\blobby_id\x18\x02 \x01(\tR\alobbyId\x122\n" +
	"\amembers\x18\x03 \x03(\v2\x18.connecttool.LobbyMemberR\amembers\"W\n" +
	"\vFriendLobby\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\blobby_id\x18\x03 \x01(\tR\alobbyId\"\x19\n" +
	"\x17GetFriendLobbiesRequest\"N\n" +
	"\x18GetFriendLobbiesResponse\x122\n" +
	"\alobbies\x18\x01 \x03(\v2\x18.connecttool.FriendLobbyR\alobbies\"=\n" +
	"\x13InviteFriendRequest\x12&\n" +
	"\x0ffriend_steam_id\x18\x01 \x01(\tR\rfriendSteamId\"0\n" +
	"\x14InviteFriendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x0fStartVPNRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04mask\x18\x02 \x01(\tR\x04mask\"F\n" +
	"\x10StartVPNResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eStopVPNRequest\"+\n" +
	"\x0fStopVPNResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc7\x01\n" +
	"\bVPNStats\x12!\n" +
	"\fpackets_sent\x18\x01 \x01(\x04R\vpacketsSent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12)\n" +
	"\x10packets_received\x18\x03 \x01(\x04R\x0fpacketsReceived\x12%\n" +
	"\x0ebytes_received\x18\x04 \x01(\x04R\rbytesReceived\x12'\n" +
	"\x0fpackets_dropped\x18\x05 \x01(\x04R\x0epacketsDropped\"\x15\n" +
	"\x13GetVPNStatusRequest\"\x99\x01\n" +
	"\x14GetVPNStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\blocal_ip\x18\x02 \x01(\tR\alocalIp\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12+\n" +
	"\x05stats\x18\x04 \x01(\v2\x15.connecttool.VPNStatsR\x05stats\"I\n" +
	"\bVPNRoute\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\rR\x02ip\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bis_local\x18\x03 \x01(\bR\aisLocal\"\x1b\n" +
	"\x19GetVPNRoutingTableRequest\"K\n" +
	"\x1aGetVPNRoutingTableResponse\x12-\n" +
	"\x06routes\x18\x01 \x03(\v2\x15.connecttool.VPNRouteR\x06routes2\xa3\a\n" +
	"\x12ConnectToolService\x12J\n" +
	"\tInitSteam\x12\x1d.connecttool.InitSteamRequest\x1a\x1e.connecttool.InitSteamResponse\x12P\n" +
	"\vCreateLobby\x12\x1f.connecttool.CreateLobbyRequest\x1a .connecttool.CreateLobbyResponse\x12J\n" +
	"\tJoinLobby\x12\x1d.connecttool.JoinLobbyRequest\x1a\x1e.connecttool.JoinLobbyResponse\x12M\n" +
	"\n" +
	"LeaveLobby\x12\x1e.connecttool.LeaveLobbyRequest\x1a\x1f.connecttool.LeaveLobbyResponse\x12S\n" +
	"\fGetLobbyInfo\x12 .connecttool.GetLobbyInfoRequest\x1a!.connecttool.GetLobbyInfoResponse\x12_\n" +
	"\x10GetFriendLobbies\x12$.connecttool.GetFriendLobbiesRequest\x1a%.connecttool.GetFriendLobbiesResponse\x12S\n" +
	"\fInviteFriend\x12 .connecttool.InviteFriendRequest\x1a!.connecttool.InviteFriendResponse\x12G\n" +
	"\bStartVPN\x12\x1c.connecttool.StartVPNRequest\x1a\x1d.connecttool.StartVPNResponse\x12D\n" +
	"\aStopVPN\x12\x1b.connecttool.StopVPNRequest\x1a\x1c.connecttool.StopVPNResponse\x12S\n" +
	"\fGetVPNStatus\x12 .connecttool.GetVPNStatusRequest\x1a!.connecttool.GetVPNStatusResponse\x12e\n" +
	"\x12GetVPNRoutingTable\x12&.connecttool.GetVPNRoutingTableRequest\x1a'.connecttool.GetVPNRoutingTableResponseB\x1cZ\x1aConnectToolCLI/connecttoolb\x06proto3"

var (
	file_connect_tool_proto_rawDescOnce sync.Once
	file_connect_tool_proto_rawDescData []byte
)

func file_connect_tool_proto_rawDescGZIP() []byte {
	file_connect_tool_proto_rawDescOnce.Do(func() {
		file_connect_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_tool_proto_rawDesc), len(file_connect_tool_proto_rawDesc)))
	})
	return file_connect_tool_proto_rawDescData
}

var file_connect_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_connect_tool_proto_goTypes = []any{
	(*InitSteamRequest)(nil),           // 0: connecttool.InitSteamRequest
	(*InitSteamResponse)(nil),          // 1: connecttool.InitSteamResponse
	(*CreateLobbyRequest)(nil),         // 2: connecttool.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),        // 3: connecttool.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),           // 4: connecttool.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),          // 5: connecttool.JoinLobbyResponse
	(*LeaveLobbyRequest)(nil),          // 6: connecttool.LeaveLobbyRequest
	(*LeaveLobbyResponse)(nil),         // 7: connecttool.LeaveLobbyResponse
	(*LobbyMember)(nil),                // 8: connecttool.LobbyMember
	(*GetLobbyInfoRequest)(nil),        // 9: connecttool.GetLobbyInfoRequest
	(*GetLobbyInfoResponse)(nil),       // 10: connecttool.GetLobbyInfoResponse
	(*FriendLobby)(nil),                // 11: connecttool.FriendLobby
	(*GetFriendLobbiesRequest)(nil),    // 12: connecttool.GetFriendLobbiesRequest
	(*GetFriendLobbiesResponse)(nil),   // 13: connecttool.GetFriendLobbiesResponse
	(*InviteFriendRequest)(nil),        // 14: connecttool.InviteFriendRequest
	(*InviteFriendResponse)(nil),       // 15: connecttool.InviteFriendResponse
	(*StartVPNRequest)(nil),            // 16: connecttool.StartVPNRequest
	(*StartVPNResponse)(nil),           // 17: connecttool.StartVPNResponse
	(*StopVPNRequest)(nil),             // 18: connecttool.StopVPNRequest
	(*StopVPNResponse)(nil),            // 19: connecttool.StopVPNResponse
	(*VPNStats)(nil),                   // 20: connecttool.VPNStats
	(*GetVPNStatusRequest)(nil),        // 21: connecttool.GetVPNStatusRequest
	(*GetVPNStatusResponse)(nil),       // 22: connecttool.GetVPNStatusResponse
	(*VPNRoute)(nil),                   // 23: connecttool.VPNRoute
	(*GetVPNRoutingTableRequest)(nil),  // 24: connecttool.GetVPNRoutingTableRequest
	(*GetVPNRoutingTableResponse)(nil), // 25: connecttool.GetVPNRoutingTableResponse
}
var file_connect_tool_proto_depIdxs = []int32{
	8,  // 0: connecttool.GetLobbyInfoResponse.members:type_name -> connecttool.LobbyMember
	11, // 1: connecttool.GetFriendLobbiesResponse.lobbies:type_name -> connecttool.FriendLobby
	20, // 2: connecttool.GetVPNStatusResponse.stats:type_name -> connecttool.VPNStats
	23, // 3: connecttool.GetVPNRoutingTableResponse.routes:type_name -> connecttool.VPNRoute
	0,  // 4: connecttool.ConnectToolService.InitSteam:input_type -> connecttool.InitSteamRequest
	2,  // 5: connecttool.ConnectToolService.CreateLobby:input_type -> connecttool.CreateLobbyRequest
	4,  // 6: connecttool.ConnectToolService.JoinLobby:input_type -> connecttool.JoinLobbyRequest
	6,  // 7: connecttool.ConnectToolService.LeaveLobby:input_type -> connecttool.LeaveLobbyRequest
	9,  // 8: connecttool.ConnectToolService.GetLobbyInfo:input_type -> connecttool.GetLobbyInfoRequest
	12, // 9: connecttool.ConnectToolService.GetFriendLobbies:input_type -> connecttool.GetFriendLobbiesRequest
	14, // 10: connecttool.ConnectToolService.InviteFriend:input_type -> connecttool.InviteFriendRequest
	16, // 11: connecttool.ConnectToolService.StartVPN:input_type -> connecttool.StartVPNRequest
	18, // 12: connecttool.ConnectToolService.StopVPN:input_type -> connecttool.StopVPNRequest
	21, // 13: connecttool.ConnectToolService.GetVPNStatus:input_type -> connecttool.GetVPNStatusRequest
	24, // 14: connecttool.ConnectToolService.GetVPNRoutingTable:input_type -> connecttool.GetVPNRoutingTableRequest
	1,  // 15: connecttool.ConnectToolService.InitSteam:output_type -> connecttool.InitSteamResponse
	3,  // 16: connecttool.ConnectToolService.CreateLobby:output_type -> connecttool.CreateLobbyResponse
	5,  // 17: connecttool.ConnectToolService.JoinLobby:output_type -> connecttool.JoinLobbyResponse
	7,  // 18: connecttool.ConnectToolService.LeaveLobby:output_type -> connecttool.LeaveLobbyResponse
	10, // 19: connecttool.ConnectToolService.GetLobbyInfo:output_type -> connecttool.GetLobbyInfoResponse
	13, // 20: connecttool.ConnectToolService.GetFriendLobbies:output_type -> connecttool.GetFriendLobbiesResponse
	15, // 21: connecttool.ConnectToolService.InviteFriend:output_type -> connecttool.InviteFriendResponse
	17, // 22: connecttool.ConnectToolService.StartVPN:output_type -> connecttool.StartVPNResponse
	19, // 23: connecttool.ConnectToolService.StopVPN:output_type -> connecttool.StopVPNResponse
	22, // 24: connecttool.ConnectToolService.GetVPNStatus:output_type -> connecttool.GetVPNStatusResponse
	25, // 25: connecttool.ConnectToolService.GetVPNRoutingTable:output_type -> connecttool.GetVPNRoutingTableResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_connect_tool_proto_init() }
func file_connect_tool_proto_init() {
	if File_connect_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_tool_proto_rawDesc), len(file_connect_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connect_tool_proto_goTypes,
		DependencyIndexes: file_connect_tool_proto_depIdxs,
		MessageInfos:      file_connect_tool_proto_msgTypes,
	}.Build()
	File_connect_tool_proto = out.File
	file_connect_tool_proto_goTypes = nil
	file_connect_tool_proto_depIdxs = nil
}
